In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv('../../processed_data/customers.csv')
types = pd.read_csv('../../processed_data/lda_distns.csv')
transaction = pd.read_csv('../../processed_data/database.csv')

In [3]:
names = [str(i) for i in range(25)]
types.columns = ['account_id']+names
types.head()

account_id         0         1         2         3         4         5  \
0         576  0.118368  0.000212  0.007477  0.085284  0.005008  0.000212   
1         704  0.000859  0.027608  0.000860  0.000859  0.000859  0.000859   
2         192  0.000543  0.000543  0.392860  0.000543  0.000543  0.000543   
3       10364  0.001191  0.001191  0.459827  0.001191  0.001191  0.001191   
4         497  0.000412  0.019238  0.032279  0.105024  0.390893  0.000411   

          6         7         8    ...           15        16        17  \
0  0.012573  0.000212  0.168622    ...     0.020308  0.042442  0.000212   
1  0.019092  0.000859  0.000860    ...     0.000859  0.000859  0.000859   
2  0.000543  0.007720  0.000543    ...     0.000543  0.000543  0.000543   
3  0.001191  0.001191  0.001191    ...     0.001191  0.001191  0.001191   
4  0.000412  0.015450  0.000412    ...     0.000412  0.000412  0.000412   

         18        19        20        21        22        23        24  
0  0.081874  0.003604  0.116314  0.085687  0.181844  0.000212  0.003120  
1  0.218398  0.000859  0.000859  0.188473  0.000859  0.000859  0.000860  
2  0.249266  0.000543  0.000543  0.204132  0.000543  0.000543  0.014677  
3  0.220206  0.001191  0.001191  0.001191  0.001191  0.001191  0.001191  
4  0.210518  0.000412  0.000412  0.000412  0.000412  0.000412  0.000411  

[5 rows x 26 columns]

In [4]:
customers.head()

Unnamed: 0  account_id  district_id  frequency        date             A2  \
0           0         576           55          0  1993-01-01  Brno - venkov   
1           1         704           55          0  1993-01-01  Brno - venkov   
2           2         192           55          0  1993-01-08  Brno - venkov   
3           3       10364           55          0  1993-01-17  Brno - venkov   
4           4         497           55          0  1993-04-15  Brno - venkov   

              A3      A4  A5  A6  A7  A8  A9   A10   A11   A12   A13  A14  \
0  south Moravia  157042  49  70  18   0   9  33.9  8743  1.88  2.43  111   
1  south Moravia  157042  49  70  18   0   9  33.9  8743  1.88  2.43  111   
2  south Moravia  157042  49  70  18   0   9  33.9  8743  1.88  2.43  111   
3  south Moravia  157042  49  70  18   0   9  33.9  8743  1.88  2.43  111   
4  south Moravia  157042  49  70  18   0   9  33.9  8743  1.88  2.43  111   

    A15   A16  
0  3659  3894  
1  3659  3894  
2  3659  3894  
3  3659  3894  
4  3659  3894

In [19]:
data = pd.merge(customers, types, on='account_id')[['account_id', 'A4', 'A11', 'A13', 'A16']+names]

In [20]:
data.shape

(4499, 30)

In [21]:
transaction.head()

Unnamed: 0  account_id  trans_id  category  payee k-symbol        date  \
0           0           1         5         0   1288       -1  1995-03-24   
1           1           1       199        29   1072       -1  1995-04-13   
2           2           1   3530438        40    911        2  1995-04-23   
3           3           1         6         0    381       -1  1995-04-30   
4           4           1       200        46    180       -1  1995-05-13   

       amount  mean_income  Initial Balance  
0  122.633333  1358.788889        33.333333  
1  420.000000  1358.788889        33.333333  
2    0.640000  1358.788889        33.333333  
3  122.633333  1358.788889        33.333333  
4   70.000000  1358.788889        33.333333

In [22]:
# Need only mean income from the transactions table
calc_income = transaction[['account_id', 'mean_income']]
prevWarn    = pd.options.mode.chained_assignment
pd.options.mode.chained_assignment = None  # default='warn' --> ignore in place warning
calc_income.drop_duplicates(inplace=True)
pd.options.mode.chained_assignment = prevWarn
print(calc_income.shape)
calc_income.head()

(4500, 2)


account_id  mean_income
0              1  1358.788889
238            2  7191.931004
715            3  2902.271667
831            4  2084.311702
1016           5  2062.000000

In [23]:
data = pd.merge(data, calc_income, on='account_id', how='left')[['account_id', 'mean_income','A4', 'A11', 'A13', 'A16']+names]

In [24]:
data.shape

(4499, 31)

In [25]:
data['A16'] = data['A16']/data['A4']

In [30]:
# Not sure what this is for...
if False:
    data = data[data['amount']>0]

In [129]:
x = data[['mean_income','A4','A11','A13','A16']].as_matrix()
y = data[names].as_matrix()

In [130]:
print(x.shape, y.shape)

(4499, 5) (4499, 25)


In [131]:
data[['mean_income','A4','A11','A13','A16']].head(10)
#data[['A4','A11','A13','A16']].drop_duplicates()  # >> only 77 unique combinations of these 4 variables across 4500.

mean_income      A4   A11   A13       A16
0   3072.195270  157042  8743  2.43  0.024796
1   9367.563265  157042  8743  2.43  0.024796
2   2066.260870  157042  8743  2.43  0.024796
3   7579.751176  157042  8743  2.43  0.024796
4   8185.426733  157042  8743  2.43  0.024796
5  14655.634101  157042  8743  2.43  0.024796
6   8256.462312  157042  8743  2.43  0.024796
7   3472.171176  157042  8743  2.43  0.024796
8   2735.714286  157042  8743  2.43  0.024796
9   4889.432510  157042  8743  2.43  0.024796

In [132]:
data[names].head()

0         1         2         3         4         5         6  \
0  0.118368  0.000212  0.007477  0.085284  0.005008  0.000212  0.012573   
1  0.000859  0.027608  0.000860  0.000859  0.000859  0.000859  0.019092   
2  0.000543  0.000543  0.392860  0.000543  0.000543  0.000543  0.000543   
3  0.001191  0.001191  0.459827  0.001191  0.001191  0.001191  0.001191   
4  0.000412  0.019238  0.032279  0.105024  0.390893  0.000411  0.000412   

          7         8         9    ...           15        16        17  \
0  0.000212  0.168622  0.000212    ...     0.020308  0.042442  0.000212   
1  0.000859  0.000860  0.000859    ...     0.000859  0.000859  0.000859   
2  0.007720  0.000543  0.000543    ...     0.000543  0.000543  0.000543   
3  0.001191  0.001191  0.001191    ...     0.001191  0.001191  0.001191   
4  0.015450  0.000412  0.000412    ...     0.000412  0.000412  0.000412   

         18        19        20        21        22        23        24  
0  0.081874  0.003604  0.116314  0.085687  0.181844  0.000212  0.003120  
1  0.218398  0.000859  0.000859  0.188473  0.000859  0.000859  0.000860  
2  0.249266  0.000543  0.000543  0.204132  0.000543  0.000543  0.014677  
3  0.220206  0.001191  0.001191  0.001191  0.001191  0.001191  0.001191  
4  0.210518  0.000412  0.000412  0.000412  0.000412  0.000412  0.000411  

[5 rows x 25 columns]

In [133]:
np.sum(y,0)/4499


array([ 0.02274455,  0.00967676,  0.06122619,  0.02933991,  0.02409954,
        0.09842417,  0.0293924 ,  0.01161045,  0.02527735,  0.01901109,
        0.02367406,  0.01231438,  0.015658  ,  0.06343827,  0.07337881,
        0.03240909,  0.02277001,  0.04177651,  0.10678996,  0.01366191,
        0.04463884,  0.11720082,  0.08587615,  0.00692295,  0.00868782])

In [134]:
y2 = np.copy(y)
for ii in range(y.shape[0]):
    y[ii,] = np.random.multinomial(1, y2[ii,])

In [137]:
y[1:10,]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
      

In [154]:
# Now we build MLP:
# =======================

import numpy, sys, json, hashlib, time

import keras
import keras.models, keras.layers.recurrent
from keras.layers.core import Dense
from keras.layers.recurrent import SimpleRNN, LSTM
from keras.layers.normalization import BatchNormalization
from six.moves import range
from six import print_
from sklearn.preprocessing import StandardScaler

input_dim       = 5
nSamples        = x.shape[0]
output_dim      = y.shape[1]
mid_level_width = 100

# Dummy inputs for testing...
#x=numpy.random.uniform(size=(nSamples,input_dim))
#y=numpy.zeros((nSamples,output_dim))

nn              =keras.models.Sequential()
nn.add(Dense(mid_level_width,input_shape=(input_dim,),activation="relu"))
nn.add(Dense(mid_level_width,activation="relu"))
nn.add(Dense(output_dim,activation="softmax"))
#op              = keras.optimizers.rmsprop(lr=1)
op              = keras.optimizers.Adam(lr=0.0008, beta_1=0.9, beta_2=0.999, epsilon=1e-8)

nn.compile(loss='mean_squared_error', optimizer=op,metrics = ["accuracy"])
nn.summary()

scaler = StandardScaler()
scaled_x = scaler.fit_transform(x)

nn.fit(scaled_x,y2,nb_epoch=50,verbose=1,shuffle=0,batch_size=134)
print ("exiting at "+ time.strftime("%Y-%m-%d %H:%M:%S"))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_126 (Dense)            (None, 100)               600       
_________________________________________________________________
dense_127 (Dense)            (None, 100)               10100     
_________________________________________________________________
dense_128 (Dense)            (None, 25)                2525      
Total params: 13,225.0
Trainable params: 13,225
Non-trainable params: 0.0
_________________________________________________________________


/Users/alexbird/anaconda3/lib/python3.5/site-packages/keras/models.py:826: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/50
4499/4499 [==============================] - 0s - loss: 0.0124 - acc: 0.0982     
Epoch 2/50
4499/4499 [==============================] - 0s - loss: 0.0080 - acc: 0.1180     
Epoch 3/50
4499/4499 [==============================] - 0s - loss: 0.0074 - acc: 0.1247     
Epoch 4/50
4499/4499 [==============================] - 0s - loss: 0.0075 - acc: 0.1289     
Epoch 5/50
4499/4499 [==============================] - 0s - loss: 0.0073 - acc: 0.1236     
Epoch 6/50
4499/4499 [==============================] - 0s - loss: 0.0072 - acc: 0.1323     
Epoch 7/50
4499/4499 [==============================] - 0s - loss: 0.0072 - acc: 0.1291     
Epoch 8/50
4499/4499 [==============================] - 0s - loss: 0.0072 - acc: 0.1258     
Epoch 9/50
4499/4499 [==============================] - 0s - loss: 0.0071 - acc: 0.1307     
Epoch 10/50
4499/4499 [==============================] - 0s - loss: 0.0071 - acc: 0.1351     
Epoch 11/50
4499/4499 [==============================] - 0s - loss: 0

In [164]:
import pickle 
with open("hsbc-x.pickle", "wb") as f:
    pickle.dump(x, f)

with open("hsbc-y.pickle", "wb") as f:
    pickle.dump(y2, f)

In [165]:
with open("predict.pickle", "rb") as f:
    pred = pickle.load(f)

In [163]:
with open("hsbc-y.pickle", "rb") as f:
    y2tmp = pickle.load(f)

In [170]:
for ii in range(10):
    print(pred[ii,])
    print(y2[ii,])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.]
[ 0.11836779  0.00021242  0.00747723  0.08528408  0.00500827  0.00021247
  0.01257288  0.00021243  0.16862208  0.00021246  0.01622526  0.00021244
  0.01489065  0.00021247  0.03465926  0.02030765  0.04244202  0.00021246
  0.08187373  0.00360396  0.11631447  0.08568698  0.18184395  0.00021243
  0.00312015]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.]
[ 0.00085949  0.02760754  0.00085953  0.00085947  0.00085937  0.00085939
  0.01909207  0.00085949  0.00085954  0.00085943  0.23033955  0.04600051
  0.09272711  0.00085948  0.16275114  0.00085932  0.00085936  0.00085945
  0.21839815  0.00085938  0.00085948  0.18847346  0.00085942  0.00085936
  0.00085951]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.]
[ 0.00054318  0.00054315  0.39286025  0.00054326  0.0005432   0.0005431
  0.000

In [162]:
x

array([[  3.07219527e+03,   1.57042000e+05,   8.74300000e+03,
          2.43000000e+00,   2.47959145e-02],
       [  9.36756327e+03,   1.57042000e+05,   8.74300000e+03,
          2.43000000e+00,   2.47959145e-02],
       [  2.06626087e+03,   1.57042000e+05,   8.74300000e+03,
          2.43000000e+00,   2.47959145e-02],
       ..., 
       [  2.29369636e+03,   5.84000000e+04,   8.62000000e+03,
          1.25000000e+00,   1.91267123e-02],
       [  7.11929556e+03,   5.84000000e+04,   8.62000000e+03,
          1.25000000e+00,   1.91267123e-02],
       [  3.63549273e+03,   5.84000000e+04,   8.62000000e+03,
          1.25000000e+00,   1.91267123e-02]])

In [120]:
from sklearn.ensemble import ExtraTreesClassifier
rforest=ExtraTreesClassifier(n_estimators=10,max_depth=6)
category_y2 = np.argmax(y2,1)
print(category_y2[:13])
rforest.fit(x,np.argmax(y2,1))
sum(rforest.predict(x)==category_y2)


(4499,)
[22 10  2  2  4 18 22 18 20 23 13  4 18]


955

In [155]:
pred = nn.predict(x)
print(pred)

[[ 9245.48339844  8535.58007812     0.         ...,     0.             0.
      0.        ]
 [ 9465.40136719  8207.3046875      0.         ...,     0.             0.
      0.        ]
 [ 9209.86621094  8587.9609375      0.         ...,     0.             0.
      0.        ]
 ..., 
 [ 3603.79980469  3242.28808594     0.         ...,     0.             0.
      0.        ]
 [ 3674.65283203  3001.11108398     0.         ...,     0.             0.
      0.        ]
 [ 3636.46801758  3165.74047852     0.         ...,     0.             0.
      0.        ]]


In [153]:
import numpy as np 
pred     = np.asarray(pred)
uq_array = set([tuple(row) for row in pred])
uq_array

{(0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0),
 (0.0,
  0.0,
  1.6587197e-38,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0),
 (0.0,
  0.0,
  2.519385e-38,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0),
 (0.0,
  0.0,
  2.5690753e-38,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0),
 (0.0,
  0.0,
  2.8000374e-37,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0),
 (0.0,
  0.0,
  4.5449096e-37,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
 

list